name: Convert txt to mrs

on:
  push:
    paths:
      - 'rule-providers/*/*.txt'

jobs:

  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest mihomo version
      run: |
        TAG=$(curl -s "https://api.github.com/repos/MetaCubeX/mihomo/tags" | jq -r '.[0].name' | tr -d 'v')
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Download mihomo
      run: |
        curl -SsL "https://github.com/MetaCubeX/mihomo/releases/download/v${TAG}/mihomo-linux-amd64-v${TAG}.gz"
        gzip -d mihomo-linux-amd64-v${TAG}.gz
        mv mihomo-linux-amd64 /usr/bin/clash-meta

    - uses: actions/checkout@v4
    
    - name: Run convert script
      run: |
        cd rule-providers
        ./convert.sh
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-convert txt to mrs
        branch: main